webtalk_init -webtalk_dir D:/Usuario/Desktop/Loading-Belt-VHDL-structure/loading_belt/loading_belt.sim/sim_1/behav/xsim/xsim.dir/manager_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 21 18:08:51 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ad1e59ff-ae85-442b-bea0-9d1eb1c23885" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "98453087b8004fa0bbcdf6252eaaa45e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "97" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "20.98_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13432_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1406148489 -regid "" -xml D:/Usuario/Desktop/Loading-Belt-VHDL-structure/loading_belt/loading_belt.sim/sim_1/behav/xsim/xsim.dir/manager_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Usuario/Desktop/Loading-Belt-VHDL-structure/loading_belt/loading_belt.sim/sim_1/behav/xsim/xsim.dir/manager_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Usuario/Desktop/Loading-Belt-VHDL-structure/loading_belt/loading_belt.sim/sim_1/behav/xsim/xsim.dir/manager_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
